## mysql image version
## ref: https://hub.docker.com/r/library/mysql/tags/
##
image: "mysql"
imageTag: "5.7.21"

tolerations: 
  - key: "mysql" 
    operator: "Equal"
    value: "exits"
    effect: "NoSchedule"
  - key: "redis" 
    operator: "Equal"
    value: "exits"
    effect: "NoSchedule"
## Specify password for root user
##
## Default: random 10 character string
mysqlRootPassword: "haima123outfox"

## Create a database user
##
# mysqlUser:
# mysqlPassword:

## Create a database
##
# mysqlDatabase:

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
##
imagePullPolicy: IfNotPresent

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m
