apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "mysql.fullname" . }}
  name: {{ template "mysql.fullname" . }}
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: {{ template "mysql.fullname" . }}